### ISSUE TITLE
unknown client.Point field 'Name' in struct literal

### ISSUE THREAD

**Issue by nautes** [torhve/infping#1]
@torhve,

When I attempt to execute _infping.go_, I get the following error message:

```
# go run /opt/infping/infping.go 
# command-line-arguments
/opt/infping/infping.go:103: unknown client.Point field 'Name' in struct literal
```

I've created a _config.toml_ file following the example that points to the InfluxDB currently running on the same instance.

Environment settings:
- InfluxDB 0.9.0
- Golang 1.3.3
- fping 3.10
- Debian Wheezy

Will really appreciate if you could suggest what might be causing this.

Regards,

**Comment by nautes** [comment]
@torhve,

It seems that 'Name' property has been replaced by 'Measurement' in InfluxDB. Would you please confirm if this is the case? It fixed the issue on my side, but I want to confirm whether this occurred due to a configuration error from my side or not.

``` go
    pts[0] = client.Point{
        Measurement: "ping",
        Tags: map[string]string{
            "host": host,
        },
```

Regards,

**Comment by torhve** [comment]
I haven't upgraded to 0.9 yet, so I think you are correct that the property has changed name during release candidate to final.

**Comment by torhve** [comment]
I changed Name to Measurement in my own source, looks to be working fine.
Thanks for the heads up.
